export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_PENDING = 'FETCH_FAVORITES_PENDING';
export const FETCH_FAVORITES_FULLFILLED = 'FETCH_FAVORITES_FULLFILLED';
export const FETCH_FAVORITES_REJECTED = 'FETCH_FAVORITES_REJECTED';
